apiVersion: v1
kind: Service
metadata:
  labels:
    app: kustomize-configuration-sample-nginx
  name: kustomize-configuration-sample-service
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: kustomize-configuration-sample-nginx
  type: LoadBalancer
